###
POST http://localhost:9000/api/signup
Content-Type: application/json

{
    "email":"sandeep.yadav4@incedoinc.com",
    "password":"Test"
}

###

POST http://localhost:9000/api/login
Content-Type: application/json

{
    "email":"sandeep.yadav4@incedoinc.com",
    "password":"Test"
}